all:
#	g++ -I/usr/include/eigen3 -O2	singularity_analyzer.cc -o singtrack -lgmsh
#	g++ -I/usr/include/eigen3 -O2	singularity_analyzer_gmsh_v2.cc -o singtrack_gmsh_v2 -lgmsh
	g++ -I/usr/include/eigen3 -O2	singularity_analyzer_gmsh_multifile.cc -o singtrack_gmsh_multifile -lgmsh
	#g++ -I/usr/include/eigen3 -O2	singularity_analyzer_gmsh_multifile_v2.cc -o singtrack_gmsh_multifile_v2 -lgmsh
