all:
	g++ -I/usr/include/eigen3 -O2	singularity_analyzer_gmsh_multifile_Q.cc -o singtrack_gmsh_multifile_Q -lgmsh
	g++ -I/usr/include/eigen3 -O2	singularity_analyzer_gmsh_multifile_Q_Gouraud.cc -o singtrack_gmsh_multifile_Q_Gouraud -lgmsh
